name: update_ios_task


on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 4,16 * * *'
  repository_dispatch:
    types: update_ios_task
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    #if: GIT_HUB.event.repository.owner.id == GIT_HUB.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ GIT_HUB.repository }}

      - name: "更新iOS端3大订阅软件订阅配置"
        run: |
          bash update_task.sh
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name lxk0301
          git add .
          git commit -m "更新iOS端3大软件订阅配置 by lxk0301 GIT_HUB Action" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/GIT_HUB-push-action@master
        with:
          GIT_HUB_token: ${{ secrets.TOKEN }}
          branch: master
